worker_processes  1;
error_log  "C:/Users/sande/OneDrive/Desktop/SSE_FIX/nginx-1.31.1/logs/duphdr-error.log"  info;
pid        "C:/Users/sande/OneDrive/Desktop/SSE_FIX/nginx-1.31.1/logs/duphdr.pid";
events { worker_connections 256; }
http {
    access_log off;
    server {
        listen 127.0.0.1:4088;
        location / {
            proxy_pass http://127.0.0.1:4001;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_buffering off;
            proxy_cache off;
            proxy_read_timeout 1h;
        }
    }
}
